fastify/fastify-cors

index.js

I think we should put this as back as we could?

preValidation -> onRequest

---

.editorconfig
.gitignore
.travis.yml
index.d.ts
package.json
test/cors.test.js
test/types/index.ts
test/types/tsconfig.json

Motivation: [see here](https://github.com/fastify/fastify-static/issues/66#issuecomment-460159590)
This PR adds the typings of DefinitelyTyped to the org repo as that seems to be the consensus now.

feat: add typings to repository

---

README.md

Fixes https://github.com/fastify/fastify-cors/issues/21

clarify where options goes

---

package.json

update standard typescript plugins

---

package.json

chore(package): update @types/node to version 12.12.7

---

package.json

chore(package): update @typescript-eslint/eslint-plugin to version 2.10.0

---

index.d.ts
test/index.test-d.ts

Export originCallback and originFunction

---

test/index.test.js

test: test for access-control-request-headers scenario (#77)

---

test/index.test.js

test: test for array and regex origin options (#77)

---

README.md

Mention maxAge is in seconds

---

README.md

docs(readme): grammatical fixes

---

index.js
test/cors.test.js

fix: https://github.com/fastify/fastify-cors/issues/127

feat: do no write header in case of non validation

---

package.json

build(deps-dev): bump @typescript-eslint/eslint-plugin from 4.33.0 to 5.12.1

---

.github/workflows/ci.yml
index.js
package.json

Updated to Fastify v4

---

README.md

This PR updates the link to fastify 1.x compatible version of this plugin since https://github.com/fastify/fastify-cors/tree/1.x is dead.

docs: update link to fastify 1.x compatible version

---

README.md

Missed requested changes from https://github.com/fastify/fastify-cors/pull/205

docs(readme): update example

---

README.md
bench.js

chore: replace use of deprecated variadic `listen()`

---

.github/workflows/ci.yml
package.json

add pre-commit hook and run linting in workflow

---

vary.js

Importing in this way can reduce the bundle size when it is needed to package into a single file.

Reduce bundle size

---

types/index.test-d.ts

See https://github.com/fastify/fastify-helmet/issues/236

test(index): replace `typeof` undefined check

---

.github/workflows/ci.yml
.taprc
package.json
test/hooks.test.js

Ref: [fastify/fastify#5116](https://github.com/fastify/fastify/issues/5116)

feat: preparation for fastify@5

---

README.md

docs(readme): standardize compatibility table style
