index.d.ts, test/types/index.ts
This PR solve issue #23. Misleading type definition makes a custom function for `origin` options doesn't work.
=> Fix TS definition

package.json, test/cors.test.js
=> Updated fastify and fixed broken tests

README.md, index.d.ts, index.js, test/cors.test.js
This PR adds the possibility to hide the options route (that is used for preflight requests) from the documentation built using fastify-swagger
=> hide options route from the documentation built using fastify-swagger

index.js, test/cors.test.js
https://github.com/fastify/fastify-cors/issues/44
According to https://github.com/rs/cors/issues/10, the `Vary` header should always has the value: `Origin`, to avoid poisoning intermediate caches.
=> feat: always set `Vary: Origin` header (#44)

index.d.ts
Tweaked the TypeScript definitions to allow for regex and strings to be mixed in an array, and in fact allowed the full range of what "origin" could actually handle (i.e. nested arrays, and/or an array that has a boolean at some point).
NOTE: TypeScript 3.7 allows for a simpler recursive type definition, but to enable this fix for projects using earlier TS versions, the older approach - with a helper interface - is used.
- [N/A] tests and/or benchmarks are included
- [N/A] documentation is changed or added
- [?] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md) (This information doesn't appear there, though I've followed what seems like the convention from other commits)
=> refactor(types) Tweaked the TypeScript definitions to allow for regex and strings to be mixed

README.md, index.d.ts, test/types/index.ts
This pull request updates the TS type for the origin callback function to allow null as a first parameter for the callback (issue #53), this was previously requested on PR #54 but instead of changing the `originFunction` type, I propose to change the `originCallback` type. Documentation and tests have been updated as well.
=> Allow originCallback null as first param in TypeScript

index.d.ts, test/types/index.ts
I had trouble with TypeScript when using fatify-cors with a http2 fastify server. The cors headers are correctly set. The problem is only a types incompatibility between Node http and http2 servers. This fixes it by allowing both server types.
=> Add http2 server support on TypeScript type definition

README.md
Just a small documentation typo, the `fastify-cors` v3 is actually for use with `fastify` v2. Before it was suggesting support for `fastify` v3.
=> Fix Fastify version typo in README

index.js, package.json, test/index.test.js, test/vary.test.js, vary.js
NOTE:
Please consider I needed to esport the `vary` function in order to test the `else` path which is never taken otherwise.
It is just a way but I'm open to suggestions off course.
=> test: full code coverage (#77)

README.md, index.js, test/cors.test.js
Refactored implementation for readability.
These important changes were made:
1. I updated the readme to reflect the actual behavior for the value returned when the `origin` option is a function. The docs simply stated it should return `true` or `false` to allow the origin, but the implementation actually use the return value to process to the origin (i.e. it could be a string). This aligns fastify-cors [express-cors](https://github.com/expressjs/cors#configuration-options).
2. If the `origin` option is a function and returns a falsy value other than `false`, for example `undefined`, the hook generates an error. The previous implementation treated this as `*` origin which does not seem intuitive …
=> chore: refactor for clarity

README.md, index.js, test/cors.test.js
This PR makes aligns the implementation with the documentation of the `origin` option:
- any value of the `origin` option or return value of an `origin` function that is falsy **but not** false, results in an error
- a non false falsy value is not defined in the documentation, and will now be considered an error
- this aligns the behavior if `origin` is a value or a function
- before a falsy value of the `origin` option disabled CORS, but a falsy non false return value of an `origin` function set the allowed origin to `*` (any origin)
This is a follow-up PR to #99 . This PR allowed #99 to only refactor and not change functionality.
=> Stricter options

README.md, index.d.ts, index.js, test/cors.test.js, test/index.test-d.ts, test/preflight.test.js
This PR returns the previous functionality removed in #96 . Note that this is not a revert since there were other PRs and changes that still add value to fastify-cors.
As discovered in #102 , replying to preflight requests in a fastify route handler has a big disadvantage: the requests will pass through the request lifecycle and other hooks before the preflight handler executes.
Since the browser removes most header values from a preflight request (including Authentication), the request will most likely be denied by any authentication plugins added to the fastify server.
Therefore, the "best" solution is to reply to preflight requests in the hook and not call the hook callback, ending the request. …
=> fix: preflight response from hook

README.md, index.d.ts, index.js, test/cors.test.js, test/index.test-d.ts
Closes fastify/fastify-cors#106
=> feat: support configuring CORS asynchronously

.github/workflows/ci.yml, README.md
Adds MacOS and Windows OSes to CI testing
=> ci: add `matrix.os` array to test on other os 

README.md, index.d.ts, index.js, test/cors.test.js
Resolve: #129 
Changes:
- fix cors options pass by promise
- update typings
- update readme
=> fix: cors options pass by promise

index.js, test/preflight.test.js
If not provided, the `hideOptionsRoute` parameter should be set to `true`, as specified in https://github.com/fastify/fastify-cors/blob/master/README.md
=> Fix hideOptionsRoute default behavior

README.md
Current origin checking in README will pass the request from non-localhost like `https://evil-localhost.test`.
This PR aim to make example code more strict.
=> docs: fix origin checking examples

index.js, test/cors.test.js
Fixes #151
This pull-request contains the code update (Regex.test replaced by String.match function), as well as the update to the tests (The tests now use a global regex, and repeats the test two times to test consistency)
```
> fastify-cors@6.0.2 test
> npm run lint && npm run unit && npm run typescript
> fastify-cors@6.0.2 lint
> npm run lint:standard && npm run lint:typescript
> fastify-cors@6.0.2 lint:standard
> standard
> fastify-cors@6.0.2 lint:typescript
> standard --parser @typescript-eslint/parser --plugin @typescript-eslint/eslint-plugin test/*.ts
> fastify-cors@6.0.2 unit
> tap test/*.test.js
PASS  test/vary.test.js 1 OK 6.878ms
PASS  test/preflight.test.js 51 OK 168.181ms
PASS  test/cors.test.js 139 OK 236.792ms
🌈 SUMMARY RESULTS 🌈  
Suites:   3 passed, 3 of 3 completed …
```
=> Fix 'isRequestOriginAllowed' returns mixed results when regex is used

index.js
I'm starting a new mission: make Fastify's tracing more readable.
Right now, this cors hook is not so nice to see in zipkin (see `anonymous`):
=> chore: rename hook functions

README.md
The `OriginCallback` is defined as:
```ts
type OriginCallback = (err: Error | null, allow: boolean) => void;
```
and therefore expects a second parameter even though I think this seems redundant given you already pass in an error. Anyway the example should be fixed to avoid confusion.
=> Fix `origin` example

README.md
Closes #137
example request:
```
$ curl -H  "origin:localhost:3000"  -v http://localhost:3000/
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.77.0
> Accept: */*
> origin:localhost:3000
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< vary: Origin
< content-type: application/json; charset=utf-8
< content-length: 17
< Date: Sun, 29 May 2022 04:46:53 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host localhost left intact
{"hello":"world"}
```
=> docs: update asynchronous example

README.md
I'm trying to use this package with fastify 4.0.2, and it seems like the latest 8.x version supports it.  But, I haven't had any luck yet and maybe the rest of the docs are out of date.  But at least I think this change is accurate.
=> Update readme to mention fastify 4.x

README.md
=> Update README to Fastify v4

.npmrc, benchmark/package.json, benchmark/vary.js, index.js, package.json, test/cors.test.js, test/vary.test.js, vary.js
Will provide benchmarks later if requested, but it is about 10 % faster (before 2600 k requests/s, after 2800k requests/s)
It would be nice, if you give me feedback regarding the code.
=> improve performance

index.d.ts
=> fix(types): make definitions `nodenext` compatible

index.js, test/named-import.test-d.ts
I'm not as ambitious as #224, I'm just trying to make sure `named` exports work for `@fastify/cors`. I'm following what we already did in https://github.com/fastify/fastify
https://github.com/fastify/fastify/blob/acba25acc3e97e3598daf79537a39a5272dba7b8/fastify.js#L783-L796
```js
/**
* These export configurations enable JS and TS developers
* to consumer fastify in whatever way best suits their needs.
* Some examples of supported import syntax includes:
* - `const fastify = require('fastify')`
* - `const { fastify } = require('fastify')`
* - `import * as Fastify from 'fastify'`
* - `import { fastify, TSC_definition } from 'fastify'`
* - `import fastify from 'fastify'`
* - `import fastify, { TSC_definition } from 'fastify'`
*/
module.exports = fastify
module.exports.fastify = fastify …
```
=> expose named export

index.js, test/cors.test.js
=> add normalizeCorsOptions and handle wildcards in origin parameter

index.js
Nearly twice as fast, see https://github.com/RafaelGSS/nodejs-bench-operations/blob/main/RESULTS-v18.md#objectassign-vs-spread-operator
=> perf(index): use spread over `Object.assign()`

README.md
Inspired by what @Eomm does with his personal Fastify plugins, this should make it clearer for users.
Also fixed a tiny grammatical error.
=> docs(readme): add plugin compatibility table

test/cors.test.js
Resolves #259 
Proof that cors headers are sent when sending stream payloads 
=> test: cors headers sent when payload is stream

vary.js
- Replaced `a-zA-Z0-9_` inside character class with `\w` word character, [which is equivilent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions/Character_classes)
- Added the `u` unicode flag to every regex pattern, which [acts as a strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode#description) for regex. See https://github.com/fastify/fastify-autoload/pull/330
=> refactor(vary): use word character inside regex character class

types/index.d.ts, types/index.test-d.ts
The documentation for the `OriginCallback` function states:
> Function - set origin to a function implementing some custom logic. The function takes the request origin as the first parameter and a callback as a second (which expects the signature err [Error | null], origin), where origin is a non-function value of the origin option. Async-await and promises are supported as well.
This corrects the type. It is possible that the second parameter should be typed as `ValueOrArray<OriginType> | Promise<ValueOrArray<OriginType>>`. That last sentence is ambiguous and I haven't consulted the implementation.
=> Fix type of OriginCallback

test/cors.test.js
See https://github.com/fastify/fastify-autoload/pull/330
=> test: add `u` unicode flag to regex

index.js, test/cors.test.js, test/preflight.test.js
When we try to set cors for a route that has route params, it seems that the cors plugin fails at registering the route and any calls to that route will return a 404 instead.
=> fix: support for embedded cors for route params

index.js, test/cors.test.js, test/preflight.test.js
Revert #278 
Closes #281 
Closes #282  
=> Revert "fix: support for embedded cors for route params (#278)"

index.js, test/cors.test.js, test/hooks.test.js, test/preflight.test.js
=> Add Vary header only for non-static origin option

index.js, test/cors.test.js, test/hooks.test.js
When the options used are delegated to a function, then the origin could be dynamic and should add `vary: origin` header.
The symbol usage feels a bit hacky, but the test changes should be ok.
fixes #291
=> vary origin on delegated options

types/index.d.ts, types/index.test-d.ts
- ~[] documentation is changed or added~
The JavaScript implementation handles async functions already and also the documentation says that async-functions are supported. Just the types don't reflect that.
> *Async-await* and promises are supported as well. 
[Source](https://github.com/fastify/fastify-cors/blob/master/README.md?plain=1#L53)
```
// Allow for promises
if (result && typeof result.then === 'function') {
result.then(res => cb(null, res), cb)
}
```
[Source](https://github.com/fastify/fastify-cors/blob/master/index.js#L261)
=> add AsyncOriginFunction type

.github/workflows/ci.yml, .taprc, package.json, test/hooks.test.js
=> Merge `next` into `master`

README.md
=> docs(readme): add `options.methods` default

package.json, test/cors.test.js, test/hooks.test.js, test/preflight.test.js, test/vary.test.js
This PR migrates from `tap` to `node:test` and `c8`
=> chore: migrate from tap to node:test and c8
